
version: 2

models:

  your_project_name:
    # Applies to all models in the 'marketing' subdirectory
    marketing:
      +schema: T1
    # Applies to all models in the 'staging' subdirectory
      +name: my_first_dbt_model
        description: "A starter dbt model"
        columns:
            - name: id
              description: "The primary key for this table"
              tests:
                  - unique
                  - not_null    
    staging:
      +schema: staging_area



    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

             
